export { facebookAdapter } from "./facebookMessenger"
export { kommunicateAdapter } from "./kommunicate"
export { generalAdapter } from "./other"
export { slackAdapter } from "./slack"
export { voximplantAdapter } from "./voximplant"
export { dialogflowMessengerAdapter } from "./dialogflowMessenger"